apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: collectd-monitor
  labels:
    app: collectd-monitor
spec:
  selector:
    matchLabels:
      app: collectd-svc
  endpoints:
  - port: metrics
    interval: "3s"
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: instance
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: inst
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: collectd-monitor
  resources:
    requests:
      memory: 400Mi
