apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: collectd-monitor
  labels:
    app: collectd-monitor
spec:
  selector:
    matchLabels:
      app: collectd-svc
  endpoints:
  - port: metrics
    interval: "3s"
    scheme: https
    tlsConfig:
      ca:
        secret:
          name: collectd-certs
          key: ca.crt
      cert:
        secret:
          name: collectd-certs
          key: server.crt
      keySecret:
        name: collectd-certs
        key: server.key
      insecureSkipVerify: false
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: instance
      - sourceLabels: [__meta_kubernetes_pod_ip]
        regex: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
        replacement: $1-$2-$3-$4.collectd-svc.default.svc.cluster.local:443
        action: replace
        targetLabel: __address__
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: inst
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: collectd-monitor
  resources:
    requests:
      memory: 400Mi
