apiVersion: v1
kind: Secret
metadata:
  name: prometheus-certs
data:
  token: TVRJek5EVTJOemc1TUVGQ1EwUkZSZz09
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZpekNDQTNPZ0F3SUJBZ0lVVE1DOG9RQ2Ficm5ZMi9GNngrdCtnZk5ubHJRd0RRWUpLb1pJaHZjTkFRRU0KQlFBd1BURUxNQWtHQTFVRUJoTUNVMGN4Q3pBSkJnTlZCQWdNQWxOSE1SUXdFZ1lEVlFRS0RBdE5lVTl5Wnl3ZwpTVzVqTGpFTE1Ba0dBMVVFQXd3Q1kyRXdIaGNOTWpBeE1UQTJNRFEwTnpRMldoY05NakV4TVRBMk1EUTBOelEyCldqQlZNUXN3Q1FZRFZRUUdFd0pUUnpFTE1Ba0dBMVVFQ0F3Q1UwY3hGREFTQmdOVkJBb01DMDE1VDNKbkxDQkoKYm1NdU1TTXdJUVlEVlFRRERCcHdjbTl0WlhSb1pYVnpMWE4yWXk1a1pXWmhkV3gwTG5OMll6Q0NBaUl3RFFZSgpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQkFOSzIxbCtRYVJzaEZ5d1owalpmcXQ3SGZBSmExbWhXCkR2MDlaVVNaS09OMlJLaHNZSE9GNXRIZWhFWmNMMnkzVFM4WWJWeGxWMDdwYk9Nd2o5eElkalZuTjVzT1lCZXgKb0ZaemUyejBmUlFXa3NvZytRRlNVbndnOWJOSXA5Q1haaCsxZU9VaThZUUU2VjBCK29RU21LaGdPa1hrZENJdwpSdi9UUmt4d29RTnZGVndKTVhVL0RjSVgvMEUzM012M1hzOUNDNTBsOUkwQ2UxMEpJQ1dqaGFaV21wdFg4cmhOCnpJY0kwTTFwU0pOdXByTnZwemtBUlhySVI2RW1SY0RmWWxDcWd1aUkvRzdQZEo2NlNuV2ZlUUplTUpQMXlySWUKdEF1NENBU0pIcFBtaXF2VDlqZnFwdmZ0VFBBWTBsUnh2SVczNURtNTNIbHoyZjNKUkNyWEwxd0VtRE5BckxvQQpmMVp4TWhNalROais4cU05NXRSd0Y4ejdEVjViNkJKREg2SXpTSWMza0NZV1lDSUphdVpjTENOZkUvU1NPcUhPCnB0UWlUZkpIR2g5TStiMHlQellVOTN4dDlZUjFQMlE3aFhNeitnQVE4cTNCNVFoS1ZISzVzVHVRSFRjMG9QYmQKeTVtcjRqTG04Z1NYdVRqdVE4Uzhnd3ZjcW9xcFk0RGpHU2o0ajV0YUczc1BOaXZpR2tqTS9Cd0svRzVDOVY4eApTV1VYRk9iVVd6cklXVHlwSFdkNS82NS85YkMwK0RxZUpFSVVBQXc1OFhFZnY3U2tOQWoxTncxdExCTnZNM3IvCmdSWFJUdmJoTUVVSGdwQVdFZnJ6dDVkZ2JHeS9sOVJXcHd3MUpyanIrZDZWWnBYN0lDaEhsNjE5c3BFTDlzYVcKLzhtbEVFOXFjdGdGQWdNQkFBR2phekJwTUdjR0ExVWRFUVJnTUY2Q0duQnliMjFsZEdobGRYTXRjM1pqTG1SbApabUYxYkhRdWMzWmpnaWh3Y205dFpYUm9aWFZ6TFhOMll5NWtaV1poZFd4MExuTjJZeTVqYkhWemRHVnlMbXh2ClkyRnNnaFp3Y205dFpYUm9aWFZ6TFhOMll5NWtaV1poZFd4ME1BMEdDU3FHU0liM0RRRUJEQVVBQTRJQ0FRQ2IKa3ErSzZZVUhZZFViS043WWxyYjNqTExwazlmcCtMOGhPR0huTWJ1aTRXZElnazNodjg1ekk1WHB5V1p3cDk2SwpDcWJId3R4cW1UZVNWbFlYNVdiTGxFeTNkMXRaZTJLTWZZMzNTMjVGV3JUK2YrdjZyOTc5aFJJbE1nSHRuckx6CnlZeXp2MUR1dVNHa3c2L2I5cllCeldXb0xCTUVidjJCeWgyR01MK2I4MnM5cXBUYnJLaWpuQWNWYVgwQXBkL2IKY1UwbFdwRW1UL0RoQ3VjZis1TmxLMmNNNjZvMzBDdDVyd0lXTnhTQVRyQmx4OW1acUJIK0tWZDBqSVdpckROcAppK0I0dSsyL3NsUytWemhXMGVDOWU5UEIwMWwxN1ZPWXFaMHJ3Um52SXN4aEpMRHNOV2w3bVowYjFJN0lUQWNwCkxtcmw4cEh5V01Od2lIdmR6ejY5eEVCWnhJNUZQNWl4ZnVBLy84aVJySkdVR3crWmd4WFR3eXNRZVRNREk4Z2IKSXFQaGgyUktrVE5PZHZFOGl1cUdqVjliUXNXR3FhZmxLbTRWNXoxdWg3WTc0bEZOSFZRdGdDd0N3ZWppNTcwQwo0VDM4NUREaFBpajBrQk9ZNDdSWjF6aHRnVjkzK24yTXJPOElWMW4yeklIbkNvZytkUExneUFNUm1DRVNjdVduCjBXZ2Jkc0t5NVUvZnE2OCt6NU5Jd0UwdjhlR3hWTFpUKzZjd2VpS3ZoaDl2dDlpZnJFbUNzRXh5S1R2clYvbjAKUkZSN2JKTVJhRXZ6VXpPSnBGN092ZlI4U2RaeFRGa3d2S3JTeVZiMVJqZUJPdXo2di9jSVNlR3ZlRWFsQ3dvRwpRR1QrZUxwT1VYdTNhTWdrZjMxbUFzKzVYamdMYlFYR3kzTmNrUmJWbWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS2dJQkFBS0NBZ0VBMHJiV1g1QnBHeUVYTEJuU05sK3Ezc2Q4QWxyV2FGWU8vVDFsUkprbzQzWkVxR3hnCmM0WG0wZDZFUmx3dmJMZE5MeGh0WEdWWFR1bHM0ekNQM0VoMk5XYzNtdzVnRjdHZ1ZuTjdiUFI5RkJhU3lpRDUKQVZKU2ZDRDFzMGluMEpkbUg3VjQ1U0x4aEFUcFhRSDZoQktZcUdBNlJlUjBJakJHLzlOR1RIQ2hBMjhWWEFreApkVDhOd2hmL1FUZmN5L2RlejBJTG5TWDBqUUo3WFFrZ0phT0ZwbGFhbTFmeXVFM01od2pReldsSWsyNm1zMituCk9RQkZlc2hIb1NaRndOOWlVS3FDNklqOGJzOTBucnBLZFo5NUFsNHdrL1hLc2g2MEM3Z0lCSWtlaythS3E5UDIKTitxbTkrMU04QmpTVkhHOGhiZmtPYm5jZVhQWi9jbEVLdGN2WEFTWU0wQ3N1Z0IvVm5FeUV5Tk0yUDd5b3ozbQoxSEFYelBzTlhsdm9Fa01mb2pOSWh6ZVFKaFpnSWdscTVsd3NJMThUOUpJNm9jNm0xQ0pOOGtjYUgwejV2VEkvCk5oVDNmRzMxaEhVL1pEdUZjelA2QUJEeXJjSGxDRXBVY3JteE81QWROelNnOXQzTG1hdmlNdWJ5QkplNU9PNUQKeEx5REM5eXFpcWxqZ09NWktQaVBtMW9iZXc4MksrSWFTTXo4SEFyOGJrTDFYekZKWlJjVTV0UmJPc2haUEtrZApaM24vcm4vMXNMVDRPcDRrUWhRQUREbnhjUisvdEtRMENQVTNEVzBzRTI4emV2K0JGZEZPOXVFd1JRZUNrQllSCit2TzNsMkJzYkwrWDFGYW5ERFVtdU92NTNwVm1sZnNnS0VlWHJYMnlrUXYyeHBiL3lhVVFUMnB5MkFVQ0F3RUEKQVFLQ0FnRUFxL3NUQ1RpaXNNUFhWK1ZUVDVIUnNyYjZuaWxwNmdxamZVbkpCNjVDVXpUS1lQVGozQ1lqK0pNMwpQdjRxcnY4RS9qVmZ2UlB4cUxTWWJPM0wzUzAvWGVMNjNaRmtHTEtmZlRBUVF5TmhteTI1YlVSd09BWHEwT2xOCjRLQ2laM3ZLbklMUFE2VzduZGNzYVA4ZWF3R0ttNUsrdlNEek1KeGF0cDdJTjhlTmczSDg2dnVONUhZc1VvaW4KaTZGK2t2TTU3TXVwRXdCUmsyMjlKbmcyUnNJcWFWTXlLU3dsTFF4Q3JNd2pNQ1NJV2R6c0xuUW85anNrZWt4UgpPbFEwaG5GTW15NHdYbjdBR2VrMDlBQjBtWUFwa2ljeVd2RTRHUjA2TW41bi9OdTFtMTJGUFMxcFBzWkV0UUozCjAxZFBCQ0U0ajZOQm9XUHpjU1YvZk1YeTMweDJsNWFweDgvbFUxby90aExhT3ZNeE11Ykh5bHF2QXBDRWFtZ0wKNDdZSWxCVkEzckx6eHZxRGc3dzhBdFJJck9mWSsvdnJwSlNNNkJnVHMvWHd5TTB5TzRGa2NIUG1rc2swb05SMAordjVheURPNjBpZiszQ3VGNWRxM000eG0xU0lzRTR5YWhjMUZyeW43eWVPYmxUU01jb2QreTlkMWVxeUl4eUFpCmgyMFozV3V1T1hiQ0VtMWZ3aGxUWjlkaGhTVmx2dVpKMitYS2Rua3IxTGVlaVNzZmhRZ2MvL3BLTW9RSmZRU2wKa3dOZXZVeTc1TGZVdzMwTEdRc1RQWFRlRUFNRTkwYk4wVGZzR296TXIyanYxdTZSbStXWVpjK2JmWUxZZUs3NgpxS216b3JGL1d3MWhKVUxXNC9TSkZZdU9rSTNNSW1sdlpkQUd2eUxSaTJLTTNCb3hKMWtDZ2dFQkFQSXZMWElDClZFZ2xSMlg4ZlU3ZDAyKzBKTmF1bzhCRXQ1T1JodkVxNUNkdHhtMFQzZFpQUjFUcVNrOVIwK3BnazFlM21nVGUKTXlGbEdWTDRNQ2tOSE5mVnovbU9nK20rQkFTcWc5ZVZpVTVqOHNGMHNqeSsrT1RMc3lFd2RjZXJvTkxzWStzbQptSjl4UElBem5TSzNXOFd3RzduaUhiSkRmeXhldXMwdGx0SW9pMW03MTV5L1pzWUFnWlRZU2hYQ1dMamYvRDcrCisvL3F4UEdrTytKSDZjaEZwMjlDbmUwZ3dBeWNkbFNqZU80cmE2YVBRVGgxL29jVWszdWttdS9hN0FiTG9La3gKQW1kN3Z5WUFOMTJlYllGa250WGplWUxIdHdZdGNNbVR1Q1Q5NDNMcFIwT0hoeVZBWmVHSmVNc0hDcks2eGdrQwo2Y2VVZERxOXMvQVA3bnNDZ2dFQkFONjhFMXpVMHRLTjlMcGRIanRlZGovYUF5VFFGSllHREttelhBdWFSOHpICms4dG1wWGF1dDBOb3oyMDg4NHRCeEQrbExKaStsc0pWdzNSOEZKNFd4UUlGQXB6c0RFVWcrY29MNWNvQVpGUUcKRWJ3cjV0ODFsZWUvVmloMy9qNExxaTlPYmVJcnowS240SzUrYk14WkJxQUxmYmQ0dlQ4cUN3MWlaT1ZzRWMwZApnSnAwZitNamxxak9iN3k4S0l6TzhIaWRlNmZ5TzJVTCtRL2x1bVZ4S3dCdU5ZVW40bzBJbFU2VzlXOWhGMjlSClhHcUJKNU9PVUR1RGVIM2xXak96eDE0dGtHakY3NnhkWVRXcHh2OUluOVF6OWVjU0hxRUd0NWFvUnRJcS9UNGYKaGNGeDBYajlFQ1BPOVh6OSthTmluM1JPRms2Rkdja0RMbGVxZVY1UXkzOENnZ0VBQmk2d0lVM3Y2dHVReEFpNwpCaTFoZldPQzRUd2FFQWx4Q2tKWHlJWkl4cnpscU5rdCs0K1FpWmxsaGpyWGh3OHFFNzRySDE2d3ZYU0FQZjc1Cjg4SlM3eXVWSUpERHkwNi9lWU1FMUpjTHAwV2o1ODViMG5NcGxXV2gwQUlWcjZBdy9kRnRCNDYzckxKT1VoTi8KT21pbDNoa056Q1A2a0JkckFxMzBaTko2SENsT3pWNmZOWEFwWm5xUzFFTGxPVUw1MHRaYzhScS9RaHd6Sk53RgpiMVJZb25Vc3ZnbGNVTFphVUxnWnlUVlhHL1ZkelNXeEM0anZrM0V5QnFFQUY0bG1KeEpCcXJBR21LK3ZCSUJTCjZYL20yYnZBMWtMMVVpSlpDTDVXTjc4ZW4wc2Y2RW9PT0tvWUNCcHB2MlVzQVRyUHlobzhmZlJtRldNenlHQVoKWE5KN1N3S0NBUUVBME1lc3dxeC9mWHd3OU92S0pjNVN1MkZvNXYzZy9ndG5uVDZSdmhKODBQZ1drbWVDRy9DRAp1ajBwaWZURE9UcUpjVHNyeFhXSkxWcGszdkJjQngvQ3hUVGJFU3EyQ2FweVdqQ3kwWmx5Y2N4S25YN3RaemI4CmNBSExDaDRJQkRLODhLRHNvVDk5aExhR0JpcGRZMkxqc2V0emlTSTFDbHNuaHdFL0lFb2ZtWXZZKzI3T1hhUUQKV2ZJL2pNTTJvMTVxekRTYUw0QUFxcVFCYnlSZ2h5d0FLZVFrYU05TkxmUG91SVVLUkwvV3pyS09GUXRCaEsrMgpoMEtpRkNpRFY4bGh6T2FhNFlzQU1TcEtyNW1YL2IwZWpETzBnVWRiekliV1dmTWNoMjVpZVBQbFZjR1JuMzVlCnZhSUdQSVo0bE8waUdFd0YzczRtc0dRNThWVExkVnY0a3dLQ0FRRUFyL3B0MXFnSE1HcmgwSXFXdTNVQVV3Qk4KaFp3Z1NHcTI4QmZsUWFYZ2Rvd3hBZFVGazM4UjFZeUZGaGttMzNmM0RXWENMeGkvNkZvMGd5QVI0ZGVGUTg5VgowdE9yL1M1MlZpOFBzb0JCVFcwMGE1ZjJlYUlMVm9jWnBZMldyYTZFNGVKbGVlckpHM0tndzVmSzQ5dXl0NWdjCm5tQUFHSWo2bnZPZlFqV3Fsb2RKaitwblZqTU1STkxzRjRRWWN3MEwxdTI3cXJZSkFZbFQvOEphRm95dmpJV0kKM2F6YlFYUDhkYUlQV3poOG5uL1Npb0kvdElBMnplUzMweFoxbkJDOXdNWm5uUmxheVRVK0RaWDFmeS83VVlFZApxeEdkSGRpMktiemkxeEdmbm5wY090bzJkL3J1SHU1WDlOL3JqZVZ0UENQT2FOSnpTbmZlbVJGTm5mdzVaQT09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZXekNDQTBPZ0F3SUJBZ0lVYmtzc2tFQk04WlBlK0QrUGsxODV1OEUyckpFd0RRWUpLb1pJaHZjTkFRRU0KQlFBd1BURUxNQWtHQTFVRUJoTUNVMGN4Q3pBSkJnTlZCQWdNQWxOSE1SUXdFZ1lEVlFRS0RBdE5lVTl5Wnl3ZwpTVzVqTGpFTE1Ba0dBMVVFQXd3Q1kyRXdIaGNOTWpBeE1UQTJNRFF3TWpNeVdoY05NakV4TVRBMk1EUXdNak15CldqQTlNUXN3Q1FZRFZRUUdFd0pUUnpFTE1Ba0dBMVVFQ0F3Q1UwY3hGREFTQmdOVkJBb01DMDE1VDNKbkxDQkoKYm1NdU1Rc3dDUVlEVlFRRERBSmpZVENDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFEQ0NBZ29DZ2dJQgpBSzVmdGpESmd0aWpkUlJsY2RIZEIra2hVN3FROVUzcUtRUVRPRmhFcWxhL2J3ZUdiUVVlZkJWdFd3SU54WkhXCkpON284WXVlWWNlZmdoYmN1Sy93eXJOeldHZlRQcW9Ka2NldmpZeGpjRHdlQmlubFpiYm1TZWV4UE1oQkUwdmYKcGNEU2VXQXREdys1OWszRUdxdTRmeUhNOUNiSldybHBacWVSS2xaekkyZnNKWnVyL1B5OFVqYlZiWDB4UWJiQwp4QmoxdmtnbXNQRmZneFFyT09hYVhsTmJRNmVGQmY2TEdQbFRTVnZuYURhcG92ckVPekpJUE04UkdNc2V4eW1GCjl1Z2pxcm5BUlB6UzZWMDRsc3pJK0t0SElzcFFDRkFKTThoK0JQZUJVank0MzNSbk1GOGZoZTA3cVdwRUJvNzkKUFRaQmZOclR2bDZWc09kQ0VBcEp5YUppTldBNmVNNENjSDQwNHJvWHplVjFmUXhtb1lUZEViVHQyeWVJMUtvWQp3Z1IzRzRxeS85RWRSTlpDekZjVE5lL3hUWC84YzBXMHdLZ1hYcUc1ODNqMEFjcUMvM2F0ZHorQktJNWRmdzB3ClRsYnJISjBsbC9pbkFWR0JaQlVNSndtL0V6OGt6RlQ5K3ljNEhGbkFnY1dtYTUrSmpFVDYrbGp5TnZkVVpraEsKblFJU3I0S0w2b3JxUU9kZVk0QlNJWnJ2RWVKWnpCdktjdkxDaDZaZUZNN2QwUkQ1OWM4Q0NlRHZEMFZsck1HWAorZlJvd1R5ZVluRXdVSjV4MDhKS3prRFdtUlM5MWQ2ZkhBNCtobnV5MkEwMGRoN0JrOUdmZXNhdVdhNEVjTko1CmdPcHhQSFpRSTB5UW5URFl6UzdzaVpRSjhUdWNjMkdteS9lc0FNdHhrbHNQQWdNQkFBR2pVekJSTUIwR0ExVWQKRGdRV0JCUmxjd2JQVWlSMFUxK1RoWXBvcUtTTFVWbytIVEFmQmdOVkhTTUVHREFXZ0JSbGN3YlBVaVIwVTErVApoWXBvcUtTTFVWbytIVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCREFVQUE0SUNBUUNjCmJTMmdaQ2piTFdZa090QklPSnBxQXhUYm1uLzdneVpGc3U4eEVTejlYQzNGbE9oeXBnSkNLaGx4WXFxUUJESGEKajdIQnpJTFJpcjJsSGFRL3NwRjRrcm1LVm9Va2pNWVNlejBIcCtGSGgvZzJrb21VdW1BS3ZGWE9QS0tRSi90bQpsZFAvQnp2eDR6VFdXNG5XUGhWdVdCTEZyRU11bkhnVlQzMVE0amN4Y0R3MWFoOEJNSlNDUldUeFZVUnliZEZqCllEbHB4MGdGY2tNTFFqb1R2VlRqMDh0WWdtaDV3OE1OYXZGZFJ5czlWRjVaT2VBMVBQcCs3OVNlcm9HOEUwUXIKZGptblpDOEV2dWRtdXBLbjJ4S3FOWlZWYTIwVjNkeURUODRPQ2dZY3BDWnBsUmlXZEhvZjFjSzNwbDh3Rm1LKwordndEV1hMRFdxVmpKUXE1MGk4Y2hKU0JLUGpYT0lsRDlkcDdMTEd1aEt1QjNVQS9USWl0V1ZzQ3M3dkZVb25nCnJ1NUNPa3hwZ3REckdzenBoZFRGMVFIaU02N2hEWEF4bjJPQnFtbGwvOXBIZk1iS2I1aWpsK2YwTlZvU1FpYTUKUEEvZnh2czRBSG1YckxobXV3cmZ4TGtVU0EzNnNUSDRVL2w2d1BrK3BJWGl1Qmx4K3B1U2hkbkErVERSKzhBbgprWldyZEliRnJoVFd0SkdjWHFsODJoS0xkcHJhVDRCNGovcWF5MTd0eWZNdnd1MlViaUhQNkx0SjZtRFpvOVlpCjdraUFnSVZDM1hiSzVMaWVSNzNqZWhSNUtDMUk4ei82aFN4OWlYbXBFTEt0YmFXVG1TYUpLODhNRGsvOU9xK1YKSnk4ODVxNE1OYnlDR0V6TEV2YmF5dlZkTGxYbDMwQkFKQUE3MFlHRGV3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - image: prometheus-server-test:1.0
        imagePullPolicy : IfNotPresent
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              /usr/sbin/nginx &&
              /prometheus/prometheus --config.file=/prometheus/prometheus-server.yml --web.listen-address=:8080;
        name: prometheus
        ports:
        - containerPort: 9090
          name: metrics
        volumeMounts:
        - mountPath: /etc/prometheus/certs/
          name: tls
        - mountPath: /etc/nginx/ssl
          name: prometheus-keys
      volumes:
      - name: tls
        secret:
          secretName: collectd-certs
      - name: prometheus-keys
        secret:
          secretName: prometheus-certs
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc
  labels:
    app: prometheus-svc
spec:
  selector:
    name: prometheus
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics

